import com.esgyn.drools.Message;
import com.esgyn.drools.RulesInfoHelper;

/*
	Rules for this data:
	POINTS = 100 to start

	+5  for each filled in
	     fname
	     lname
	     city
	     state
	     zip

	+3  for state == AZ
	+5  for city == LOS ANGELES | SAN DIEGO | SAN FRANCISCO
	-25 for zip == 99999
	+5  for vehicle_make == BMW | MASERATI
	+1                   == FORD | DODGE | TOYOTA
    +2  for model_year >= 2010
    -6                 < 2000
    +5  for annual_miles < 10000
    -3                  > 25000
    +5  for use == PLEASURE
    -1          == WORK
    +7  for fav_food == CHILI DOG | FRIES
    +8  for fav_movie == STAR WARS | MINIONS
    +10 for fav_sport == CURLING | LACROSSE
    +10  for fav_team == WARRIORS | LAKERS | CELTICS

*/

dialect "mvel"
rule "Fname Entered Rule"
    when
		rih: RulesInfoHelper()
		m: Message ( fname != null )
    then
		m.incPoints(5);
		rih.getFiredRules().add(drools.getRule().getName());
		rih.getFiredTuples().add(drools.getTuple());
    	//System.out.println("fname rule");
end

rule "Lname entered"
	when
		rih: RulesInfoHelper()
		m: Message ( lname != null )
	then
		m.incPoints(5);
		rih.getFiredRules().add(drools.getRule().getName());
		rih.getFiredTuples().add(drools.getTuple());
    	//System.out.println("lname rule");
end

rule "City entered"
	when
		rih: RulesInfoHelper()
		m: Message ( city != null )
	then
		m.incPoints(5);
		rih.getFiredRules().add(drools.getRule().getName());
		rih.getFiredTuples().add(drools.getTuple());
    	//System.out.println("city rule");
end

rule "State entered"
	when
		rih: RulesInfoHelper()
		m: Message( state != null )
	then
		m.incPoints(5);
		rih.getFiredRules().add(drools.getRule().getName());
		rih.getFiredTuples().add(drools.getTuple());
    	//System.out.println("state rule");
end

rule "Zip entered"
	when
		rih: RulesInfoHelper()
		m: Message( zip != null )
	then
		m.incPoints(5);
		rih.getFiredRules().add(drools.getRule().getName());
		rih.getFiredTuples().add(drools.getTuple());
    	//System.out.println("zip rule");
end

rule "bad Zip entered"
	when
		rih: RulesInfoHelper()
		m: Message( zip == "99999" )
	then
		m.incPoints(-25);
		rih.getFiredRules().add(drools.getRule().getName());
		rih.getFiredTuples().add(drools.getTuple());
    	//System.out.println("zip 99999 rule");
end

rule "AZ Rule"
    when
		rih: RulesInfoHelper()
		m: Message ( state == "AZ" )
    then
		m.incPoints(3);
		rih.getFiredRules().add(drools.getRule().getName());
		rih.getFiredTuples().add(drools.getTuple());
    	//System.out.println("state AZ rule");
end

rule "City LAX rule"
	when
		rih: RulesInfoHelper()
		m: Message ( city == "LOS ANGELES" )
	then
		m.incPoints(6);
		rih.getFiredRules().add(drools.getRule().getName());
		rih.getFiredTuples().add(drools.getTuple());
    	//System.out.println("LAX rule");
end

rule "City SAN rule"
	when
		rih: RulesInfoHelper()
		m: Message ( city == "SAN DIEGO" )
	then
		m.incPoints(5);
		rih.getFiredRules().add(drools.getRule().getName());
		rih.getFiredTuples().add(drools.getTuple());
    	//System.out.println("SAN rule");
end

rule "City SFO rule"
	when
		rih: RulesInfoHelper()
		m: Message ( city == "SAN FRANCISCO" )
	then
		m.incPoints(4);
		rih.getFiredRules().add(drools.getRule().getName());
		rih.getFiredTuples().add(drools.getTuple());
    	//System.out.println("SFO rule");
end

rule "Vehicle rule 1"
	when
		rih: RulesInfoHelper()
		m: Message ( vehicle_make in ("BMW", "MASERATI"))
	then
		m.incPoints(5);
		rih.getFiredRules().add(drools.getRule().getName());
		rih.getFiredTuples().add(drools.getTuple());
    	//System.out.println("BMW rule");
end

rule "Vehicle rule 2"
	when
		rih: RulesInfoHelper()
		m: Message ( vehicle_make in ("FORD", "DODGE", "TOYOTA"))
	then
		m.incPoints(1);
		rih.getFiredRules().add(drools.getRule().getName());
		rih.getFiredTuples().add(drools.getTuple());
    	//System.out.println("FORD rule");
end

rule "Model yr >= 2010"
	when
		rih: RulesInfoHelper()
		m: Message ( model_year >= 2010 )
	then
		m.incPoints(2);
		rih.getFiredRules().add(drools.getRule().getName());
		rih.getFiredTuples().add(drools.getTuple());
    	//System.out.println("yr >= 2010 rule");
end

rule "Model yr < 2000"
	when
		rih: RulesInfoHelper()
		m: Message ( model_year < 2000 )
	then
		m.incPoints(-6);
		rih.getFiredRules().add(drools.getRule().getName());
		rih.getFiredTuples().add(drools.getTuple());
    	//System.out.println("yr < 2000 rule");
end

rule "Miles < 10000"
	when
		rih: RulesInfoHelper()
		m: Message ( annual_miles < 10000 )
	then
		m.incPoints(5);
		rih.getFiredRules().add(drools.getRule().getName());
		rih.getFiredTuples().add(drools.getTuple());
    	//System.out.println("miles < 10000 rule");
end

rule "Miles > 25000"
	when
		rih: RulesInfoHelper()
		m: Message ( annual_miles >= 25000 )
	then
		m.incPoints(-3);
		rih.getFiredRules().add(drools.getRule().getName());
		rih.getFiredTuples().add(drools.getTuple());
    	//System.out.println("miles > 25000 rule");
end

rule "Use Pleasure"
	when
		rih: RulesInfoHelper()
		m: Message ( use == "PLEASURE" )
	then
		m.incPoints(5);
		rih.getFiredRules().add(drools.getRule().getName());
		rih.getFiredTuples().add(drools.getTuple());
    	//System.out.println("Pleasure rule");
end

rule "Use Work"
	when
		rih: RulesInfoHelper()
		m: Message ( use == "WORK" || use == "COMMUTE" )
	then
		m.incPoints(-1);
		rih.getFiredRules().add(drools.getRule().getName());
		rih.getFiredTuples().add(drools.getTuple());
    	//System.out.println("Work rule");
end

rule "Food"
	when
		rih: RulesInfoHelper()
		m: Message ( fav_food == "CHILI DOG" || fav_food == "FRIES" )
	then
		m.incPoints(7);
		rih.getFiredRules().add(drools.getRule().getName());
		rih.getFiredTuples().add(drools.getTuple());
    	//System.out.println("Chili dog rule");
end

rule "Movie"
	when
		rih: RulesInfoHelper()
		m: Message ( fav_movie == "STAR WARS" || fav_movie == "MINIONS" )
	then
		m.incPoints(8);
		rih.getFiredRules().add(drools.getRule().getName());
		rih.getFiredTuples().add(drools.getTuple());
    	//System.out.println("Movie rule");
end

rule "Sport"
	when
		rih: RulesInfoHelper()
		m: Message ( fav_sport == "CURLING" || fav_sport == "LACROSSE" )
	then
		m.incPoints(10);
		rih.getFiredRules().add(drools.getRule().getName());
		rih.getFiredTuples().add(drools.getTuple());
    	//System.out.println("Sport rule");
end

rule "Team"
	when
		rih: RulesInfoHelper()
		m: Message ( fav_team == "WARRIORS" || fav_team == "LAKERS" || fav_team == "CELTICS" )
	then
		m.incPoints(10);
		rih.getFiredRules().add(drools.getRule().getName());
		rih.getFiredTuples().add(drools.getTuple());
    	//System.out.println("Team rule");
end
